# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "000000"
    url: jdbc:mysql://localhost:3306/dj_mall?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
# Mybatis-plus
mybatis-plus:
  type-aliases-package: com.dj.mall.product.pro.entity # 类别名
  mapper-locations: classpath:/mapper/**/*.xml # mapper文件
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射

# Dubbo
dubbo:
  application:
    name: dict-service # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  protocol:
    name: dubbo # 协议名
    port: 20883 # 服务端口
  #日志
logging:
  level:
    com.dj.mall.product.pro.mapper:
      debug
