# Dubbo
dubbo:
  application:
    name: cmpt-service # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  protocol:
    name: dubbo # 协议名
    port: 20888 # 服务端口
spring:
  mail:
    host: smtp.163.com #SMTP服务器地址
    username: zrp521zrp@163.com #登陆账号
    password: ILLFRUXCRUQEYMVP #登陆密码（或授权码）
    properties:
      from: zrp521zrp@163.com #邮件发信人（即真实邮箱）