server:
  port: 9090

spring:
  application:
    name: user-service #服务名
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
    database: 1
#连接注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true  #支持域名直接解析ip

#断路器配置
circuitBreaker:
  # 请求总数下限
  requestVolumeThreshold: 20
  # 休眠时间窗
  sleepWindowInMilliseconds: 3000
  # 错误百分比下限
  errorThresholdPercentage: 50
feign:
  hystrix:
    enabled: true