spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "000000"
    url: jdbc:mysql://localhost:3306/dj_mall?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

# Mybatis-plus
mybatis-plus:
  type-aliases-package: com.dj.cloud.pojo
  configuration:
    map-underscore-to-camel-case: true

#日志
logging:
  level:
    com.dj.cloud.mapper:
      debug

swagger:
  enabled: true

